//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dEM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoDB : DbContext
    {
        public DemoDB()
            : base("name=DemoDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<disciple> disciple { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<journal> journal { get; set; }
        public virtual DbSet<speciality> speciality { get; set; }
        public virtual DbSet<user_auth> user_auth { get; set; }
    }
}
