//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public int teacher_id { get; set; }
        public int disciple_id { get; set; }
    
        public virtual disciple disciple { get; set; }
        public virtual group group { get; set; }
        public virtual user_auth user_auth { get; set; }
    }
}
